### ISSUE TITLE
Do not hardcode the welcome message and pick it from a wiki page

### ISSUE THREAD

**Issue by srish** [srish/gerrit-newcomer-bot#3]
@Niharika29 sugggests:

> Maybe don't hardcode the message shown to the user in the bot code but have it pick it up from a mediawiki page, so it's easy to modify when needed, which I think will be frequent. So like, create a page such as [this](https://www.mediawiki.org/wiki/User:SSethi_(WMF)/Gerrit_bot_text) where the bot message goes and the bot makes an API call to get that text every time it makes a post (not too frequent, I think). 
> This will allow you to experiment with different messages more easily to see which ones are more effective without having to make a patch every time.

**Comment by srish** [comment]
Thanks, @samuelguebo :)

**Comment by samuelguebo** [comment]
You're welcome, @srish :)
